# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 23:48
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for post, also used for url', max_length=150)),
                ('content', models.TextField()),
                ('header_image', models.ImageField(upload_to=blog.models.post_upload_location)),
            ],
        ),
    ]
