# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 23:58
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='image_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(db_index=True, default='test', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to=blog.models.post_upload_location, width_field='image_width'),
        ),
    ]
