# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.CharField(default='chabadofsharon', help_text='Used in URL', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='url',
            field=models.URLField(blank=True, help_text='URL to send viewer to'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Client'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, help_text='For listing', max_length=200),
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.CharField(help_text='Used in URL', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=True, help_text='For listing', max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.CharField(help_text='Used in URL', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.CharField(blank=True, help_text='For listing', max_length=200),
        ),
        migrations.AlterField(
            model_name='type',
            name='slug',
            field=models.CharField(help_text='Used in URL', max_length=30, unique=True),
        ),
    ]
