# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20170413_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/images/portfolio'),
        ),
    ]
