# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image to display', upload_to='portfolio/images/')),
                ('alt_text', models.CharField(max_length=35)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/projects/'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='project',
            field=models.ForeignKey(help_text='Project to show the image on', on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project'),
        ),
    ]
