# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20170425_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(help_text='Image to display', upload_to=portfolio.models.gallery_upload_location),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to=portfolio.models.project_upload_location, width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='project',
            name='path_name',
            field=models.CharField(db_index=True, help_text='/projects/<path_name>', max_length=30, unique=True),
        ),
    ]
